import { Role } from "@/types";

export const roles: Role[] = [
  {
    company: "ZoltMoney",
    title: "Tech Lead",
    period: "Feb 2025 — Present",
    location: "Bengaluru",
    highlights: [
      "Architecting and building a cross-border remittance platform end to end — backend, mobile, and infrastructure",
      "Go microservices on AWS EKS covering auth, wallets, KYC, payouts and transaction history, deployed via GitOps",
      "React Native app with biometric-signed transactions, SSL pinning and hardware-backed key storage",
      "Custodial blockchain wallets across multiple chains, with automated treasury sweeps",
      "Multi-provider KYC orchestration with per-corridor routing and webhook reconciliation across six markets",
      "Event-driven notification infrastructure fanning out to push, SMS, email and websocket from one publisher",
      "Fraud surface: device identity, request nonces, velocity limits and SMS-pumping defence",
      "Leveraging Generative AI for rapid prototyping and accelerated delivery",
    ],
    tech: ["Go", "React Native", "TypeScript", "Kubernetes", "AWS", "PostgreSQL", "RabbitMQ", "GenAI"],
  },
  {
    company: "Six Sigma Sports (ST Labs)",
    title: "SDE-3 — Web3",
    period: "Jun 2022 — Feb 2025",
    location: "Bengaluru",
    highlights: [
      "Led frontend architecture for a blockchain-based betting platform on Cosmos (SGE token)",
      "Built with Remix (React + Node.js), achieving 40% better engagement and halving load times",
      "Integrated Web3Auth, OAuth2, and Synaps KYC — driving 35% engagement increase",
      "Implemented DeFi wallet integrations (Keplr, Leap, Cosmostation) across desktop & mobile",
      "Architected gRPC-based blockchain data framework powering 2 key projects",
      "Published an npm package for Cosmos message composing & broadcasting",
      "Built real-time data layer with WebSockets and intelligent fallback mechanisms",
    ],
    tech: ["Remix", "React", "CosmJS", "Web3Auth", "gRPC", "TypeScript"],
  },
  {
    company: "Paytm (One97 Communications)",
    title: "Senior Software Engineer",
    period: "Mar 2020 — May 2022",
    location: "Bengaluru",
    highlights: [
      "Hotels: Built React-based booking interface → 20% booking increase in 3 months",
      "ONDC: Improved platform interoperability by 40% and efficiency by 25%",
      "Paytm Mall: Designed return & exchange flow serving 2M+ customers",
      "Created email template system reducing design-testing iterations by 50%",
      "Seller Panel: Reduced operational issues by 35%, boosted seller satisfaction by 15%",
      "Hi5: Built group-buying platform → 30% engagement rise, 50% more transactions in 4 months",
    ],
    tech: ["React", "JavaScript", "Node.js"],
  },
  {
    company: "Trakinvest",
    title: "Senior Software Engineer",
    period: "Sep 2019 — Feb 2020",
    location: "Bengaluru",
    highlights: [
      "Revamped React-based trading platform with modern architecture",
      "Built Gatsby.js landing page with comprehensive SEO optimization",
      "Developed Next.js SSR product for improved performance",
      "Automated certificate issuance system",
      "Created dynamic event page system — 20% more participation",
    ],
    tech: ["React", "Gatsby.js", "Next.js"],
  },
  {
    company: "Good Earth",
    title: "Software Engineer",
    period: "Feb 2019 — Aug 2019",
    location: "Delhi",
    highlights: [
      "Built responsive React pages for the e-commerce platform",
      "Implemented OAuth2 social authentication",
      "Created interactive book feature using Turn.js",
      "Developed address module with map integration",
    ],
    tech: ["React", "OAuth2", "Turn.js"],
  },
  {
    company: "GlobalLogic",
    title: "Software Engineer",
    period: "Oct 2016 — Feb 2019",
    location: "Noida",
    highlights: [
      "Built Ember.js Employee Consortium Portal for DISA",
      "Developed Angular.js Employee Directory application",
      "Created CMS system for content management",
      "Built C# to Ember model converter tool",
    ],
    tech: ["Ember.js", "Angular.js", "C#"],
  },
];
